# Placeholder buildvars file

BUILD_USER = 'BUILD_USER'
BUILD_HOSTNAME = 'BUILD_HOSTNAME'
BUILD_DATE = '2026-01-00T00:00:00.000000+00:00'
BUILD_OS = 'BUILD_OS'
BUILD_ARCH = 'BUILD_ARCH'
BUILD_TYPE = 'DEBUG'
BOARD_NAME = 'posix'
BUILD_GIT_BRANCH = 'BUILD_GIT_BRANCH'
BUILD_GIT_COMMIT = 'BUILD_GIT_COMMIT'
BUILD_GIT_COMMIT_SHORT = 'BGCS'
BUILD_STRING = 'BUILD_STRING'
IS_DEBUG = True
