#!/usr/bin/env python3

import datetime
import getpass
import os
import platform
import shutil
import subprocess
from pathlib import Path


def run_git(*args: str) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def python_string(value: str) -> str:
    return repr(value)


def main() -> None:
    cwd = Path.cwd()
    source = cwd / "board"
    destination = cwd / "built"

    if not source.is_dir():
        raise SystemExit(f"Source directory does not exist: {source}")

    # Start with a clean build directory.
    if destination.exists():
        shutil.rmtree(destination)

    print(f"Copying {source} -> {destination}")
    shutil.copytree(source, destination)

    build_user = getpass.getuser()
    build_hostname = platform.node()
    build_date = datetime.datetime.now(
        datetime.timezone.utc
    ).astimezone().isoformat(timespec="seconds")

    build_git_branch = run_git("rev-parse", "--abbrev-ref", "HEAD")
    build_git_commit = run_git("rev-parse", "HEAD")

    buildvars = (
        "# This file is automatically generated during the build.\n"
        "# Do not edit manually.\n\n"
        f"BUILD_USER = {python_string(build_user)}\n"
        f"BUILD_HOSTNAME = {python_string(build_hostname)}\n"
        f"BUILD_DATE = {python_string(build_date)}\n"
        f"BUILD_GIT_BRANCH = {python_string(build_git_branch)}\n"
        f"BUILD_GIT_COMMIT = {python_string(build_git_commit)}\n"
    )

    # Example:
    # built/
    #   posix/buildvars.py
    #   windows/buildvars.py
    #   macos/buildvars.py
    for target in sorted(destination.iterdir()):
        if not target.is_dir():
            continue

        buildvars_path = target / "buildvars.py"

        print(f"Writing {buildvars_path}")
        buildvars_path.write_text(buildvars, encoding="utf-8")

    print("Build tree prepared successfully.")


if __name__ == "__main__":
    main()