#!/usr/bin/env python3

import argparse
import datetime
import getpass
import io
import platform
import shutil
import subprocess
import tokenize
from pathlib import Path


def run_git(*args: str) -> str:
    try:
        result = subprocess.run(
            ["git", *args],
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def strip_python_comments(path: Path) -> None:
    """
    Strip comments from a Python source file without damaging strings
    containing '#' characters.
    """
    try:
        source = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        print(f"Skipping non-UTF-8 Python file: {path}")
        return

    try:
        tokens = tokenize.generate_tokens(io.StringIO(source).readline)

        filtered = [
            token
            for token in tokens
            if token.type != tokenize.COMMENT
        ]

        stripped = tokenize.untokenize(filtered)

    except (tokenize.TokenError, IndentationError):
        print(f"Could not strip comments from: {path}")
        return

    path.write_text(stripped, encoding="utf-8")


def strip_comments_from_tree(root: Path) -> None:
    """
    Strip comments from all Python files beneath root.
    """
    for path in root.rglob("*.py"):
        if path.is_file():
            strip_python_comments(path)
            
def get_build_os() -> str:
    system = platform.system()

    if system == "Windows":
        # Only BuildLabEx is read from the registry.
        build_lab_ex = "unknown"

        try:
            import winreg

            with winreg.OpenKey(
                winreg.HKEY_LOCAL_MACHINE,
                r"SOFTWARE\Microsoft\Windows NT\CurrentVersion",
            ) as key:
                build_lab_ex, _ = winreg.QueryValueEx(
                    key,
                    "BuildLabEx",
                )
        except (OSError, ImportError):
            pass

        return (
            f"Windows {platform.release()} "
            f"(version {platform.version()}, "
            f"edition {platform.win32_edition()}, "
            f"BuildLabEx {build_lab_ex})"
        )

    if system == "Darwin":
        mac_version = platform.mac_ver()[0]

        try:
            build_number = subprocess.run(
                ["sw_vers", "-buildVersion"],
                check=True,
                capture_output=True,
                text=True,
            ).stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            build_number = "unknown"

        return (
            f"macOS {mac_version} "
            f"(build {build_number}, "
            f"Darwin {platform.release()})"
        )

    if system == "Linux":
        return (
            f"Linux {platform.release()} "
            f"({platform.version()})"
        )

    return platform.platform()

def generate_buildvars(
    board_name: str,
    build_type: str,
    build_user: str,
    build_hostname: str,
    build_os: str,
    build_arch: str,
    git_branch: str,
    git_commit: str,
    build_datetime: datetime.datetime,
) -> str:

    short_commit = (
        git_commit[:5]
        if git_commit != "unknown"
        else "unknown"
    )

    timestamp = build_datetime.strftime("%Y%m%d_%H%M")

    build_string = (
        f"{board_name}-"
        f"{git_branch}_"
        f"{short_commit}-"
        f"{timestamp}"
    )

    debug = build_type == "DEBUG"

    return (
        "# This file is automatically generated during the build.\n"
        "# Do not edit manually.\n\n"
        f"BUILD_USER = {build_user!r}\n"
        f"BUILD_HOSTNAME = {build_hostname!r}\n"
        f"BUILD_DATE = {build_datetime.isoformat()!r}\n"
        f"BUILD_OS = {build_os!r}\n"
        f"BUILD_ARCH = {build_arch!r}\n"
        f"BUILD_TYPE = {build_type!r}\n"
        f"BOARD_NAME = {board_name!r}\n"
        f"BUILD_GIT_BRANCH = {git_branch!r}\n"
        f"BUILD_GIT_COMMIT = {git_commit!r}\n"
        f"BUILD_GIT_COMMIT_SHORT = {short_commit!r}\n"
        f"BUILD_STRING = {build_string!r}\n"
        f"IS_DEBUG = {debug!r}\n"
    )


def build_board(
    source_root: Path,
    destination_root: Path,
    board_name: str,
    build_type: str,
    common_metadata: dict,
) -> None:

    source = source_root / board_name
    destination = destination_root / board_name

    if not source.is_dir():
        raise SystemExit(
            f"Board does not exist: {board_name!r}\n"
            f"Expected directory: {source}"
        )

    if destination.exists():
        shutil.rmtree(destination)

    print(f"Building board: {board_name}")
    print(f"  {source} -> {destination}")

    shutil.copytree(source, destination)

    buildvars = generate_buildvars(
        board_name=board_name,
        build_type=build_type,
        **common_metadata,
    )

    buildvars_path = destination / "buildvars.py"
    buildvars_path.write_text(buildvars, encoding="utf-8")

    if build_type == "PROD":
        print(f"  Stripping Python comments from {board_name}")
        strip_comments_from_tree(destination)

    print(f"  Build variables: {buildvars_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Prepare board builds and generate build metadata."
        )
    )

    parser.add_argument(
        "board",
        help=(
            "Board to build, corresponding to a directory under "
            "./board, or 'all' to build every board."
        ),
    )

    parser.add_argument(
        "--build-type",
        "-t",
        choices=("DEBUG", "PROD"),
        default="DEBUG",
        help="Build type. Default: DEBUG",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    cwd = Path.cwd()

    source_root = cwd / "board"
    destination_root = cwd / "built"

    if not source_root.is_dir():
        raise SystemExit(
            f"Board directory does not exist: {source_root}"
        )

    build_type = args.build_type.upper()

    git_branch = run_git(
        "rev-parse",
        "--abbrev-ref",
        "HEAD",
    )

    git_commit = run_git(
        "rev-parse",
        "HEAD",
    )

    # Build timestamps are always UTC so builds made on different
    # machines remain directly comparable.
    build_datetime = datetime.datetime.now(
        datetime.timezone.utc
    )

    common_metadata = {
        "build_user": getpass.getuser(),
        "build_hostname": platform.node(),
        "build_os": get_build_os(),
        "build_arch": platform.machine(),
        "git_branch": git_branch,
        "git_commit": git_commit,
        "build_datetime": build_datetime,
    }

    destination_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    if args.board.lower() == "all":
        boards = sorted(
            path.name
            for path in source_root.iterdir()
            if path.is_dir()
        )

        if not boards:
            raise SystemExit(
                f"No boards found in {source_root}"
            )

        # "all" represents a complete build, so remove any stale
        # boards from previous builds first.
        if destination_root.exists():
            shutil.rmtree(destination_root)

        destination_root.mkdir(
            parents=True,
            exist_ok=True,
        )

    else:
        boards = [args.board]

    print(f"Build type: {build_type}")
    print(f"Git branch: {git_branch}")
    print(f"Git commit: {git_commit}")
    print(f"Build OS: {common_metadata['build_os']}")
    print(f"Build arch: {common_metadata['build_arch']}")
    print()

    for board_name in boards:
        build_board(
            source_root=source_root,
            destination_root=destination_root,
            board_name=board_name,
            build_type=build_type,
            common_metadata=common_metadata,
        )

    print()
    print("Build tree prepared successfully.")


if __name__ == "__main__":
    main()